### ISSUE TITLE
100000000000000000000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by huei90** [parshap/js-is-integer#2]
```js
var num = 100000000000000000000000000000000000000000000000000000000;

parseInt(num, 10) === num; // => false
```

**Comment by parshap** [comment]
Thanks for the report. This is interesting.

```
> parseInt(1000000000000000000000, 10)
1
> parseInt("1000000000000000000000", 10)
1000000000000000000000
```

The native `Number.isInteger` returns true for `1000000000000000000000`, so we should make sure this polyfill does too. I will think about the best solution — any ideas?

**Comment by huei90** [comment]
Convert the number to string before doing parse?

**Comment by parshap** [comment]
Fixed and released in `is-integer@1.0.5`. Thanks for reporting!

**Comment by huei90** [comment]
Still fail on `100000000000000000.1`

**Comment by parshap** [comment]
That's because `100000000000000000.1` is not representable in JavaScript.

```
> 100000000000000000.1
100000000000000000
```

**Comment by parshap** [comment]
Sorry, forgot to `npm publish` 1.0.5, but did just now.
