### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by jloramas** [parshap/js-is-integer#4]
Hi @parshap, I am not using directly this package, but an application we are working with uses it. The issue is the we have to report all the licenses this application uses, and the license for this package is giving us some internal problems for using it. Is there any possibility for you to dual license it with a more common open source license like Apache 2.0 or MIT?

**Comment by parshap** [comment]
I've dual licensed with ISC in https://github.com/parshap/js-is-integer/commit/9e2282efc268747a680dfdc0c4130f76cebb0fa9. Hope that suffices.
